# Rime dictionary
# encoding: utf-8

---
name: extended
version: "2020.12.30"
sort: by_weight
vocabulary: essay-zh-hans
use_preset_vocabulary: true

import_tables:
  - dicts/pinyin_simp
  - dicts/placeless_punct
  # - dicts/clover.base
  # - dicts/clover.phrase
  # - dicts/THUOCL_animal
  # - dicts/THUOCL_caijing
  # - dicts/THUOCL_car
  # - dicts/THUOCL_chengyu
  # - dicts/THUOCL_diming
  # - dicts/THUOCL_food
  # - dicts/THUOCL_IT
  # - dicts/THUOCL_law
  # - dicts/THUOCL_lishimingren
  # - dicts/THUOCL_medical
  # - dicts/THUOCL_poem
  # - dicts/sogou_new_words
...