distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.16.0
install_time: "Fri Jun 23 22:02:35 2023"
installation_id: logb
rime_version: 1.11.2
update_time: "Fri May 24 17:16:25 2024"