# Rime dictionary
# encoding: utf-8
#

---
name: placeless_punct
version: "0.2"
sort: by_weight
...

# 个人土方
.	.	1
,	,	1
:	:	1
/	/	1
-	-	1
_	_	1
=	=	1
+	+	1
0	0	1
1	1	1
2	2	1
3	3	1
4	4	1
5	5	1
6	6	1
7	7	1
8	8	1
9	9	1
覅	fiao	128
经卦	jing gua	128
应卦	ying gua	128
震卦	zhen gua	128
江臻宇	jiang zhen yu	128
乾三连	qian san lian	128
震坎兑	zhen kan dui	128
十二长生	shi er chang sheng	128
