customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.0.0
  generator: "Rime::SwitcherSettings"
  modified_time: "Wed Mar 27 00:09:39 2024"
  rime_version: 1.8.5
patch:
  "ascii_composer/switch_key":
    Shift: noop
  key_binder:
    bindings: [{accept: Tab, send: Page_Down, when: composing}, {accept: "Shift+Tab", send: Page_Up, when: composing}]
  "menu/page_size": 6
  schema_list:
    - {schema: luna_pinyin}
    - {schema: japanese}
    - {schema: placeless_flypy}
  "switcher/hotkeys":
    - "Control+grave"