distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.15.0.0
install_time: "Fri Jun 23 22:02:35 2023"
installation_id: "3b9bcff0-77d8-45b2-8da0-07628464e6bd"
rime_version: 1.8.5
update_time: "Wed Aug 30 22:50:05 2023"